import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "@styles/global.scss";

const inter = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
