import ChartBox from "@components/chartBox/ChartBox";
import Deals from "@components/topDeals/Deals";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Dashboard = () => {
  return (
    <div className="dashboard__home">
      <div className="box box1">
        <Deals />
      </div>
      <div className="box box2">
        <ChartBox />
      </div>
      <div className="box box3">
        <ChartBox />
      </div>
      <div className="box box4">
        <ChartBox />
      </div>
      <div className="box box5">
        <ChartBox />
      </div>
      <div className="box box6">Box6</div>
      <div className="box box7">Box7</div>
      <div className="box box8">Box8</div>
      <div className="box box9">Box9</div>
    </div>
  );
};

export default Dashboard;
