import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Dashboard = () => {
  return <div>Dashboard</div>;
};

export default Dashboard;
